treewide: fix 'a function declaration without a prototype is deprecated' error with Clang > 14
Fix the following error with Clang 15:
error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]

Signed-off-by: Roberto Sartori <roberto.sartori.android@gmail.com>